### ISSUE TITLE
Filters: exporting multiline issue

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#1000]
**Describe the bug**

If the export line of of the custom-filters file is not on one line, the functions are not found

**To Reproduce**

works
![image](https://user-images.githubusercontent.com/29847057/216423590-4ade20fa-d99c-4dc5-9772-c8b9d09ab246.png)
![image](https://user-images.githubusercontent.com/29847057/216424122-6e93aabe-3cb1-4952-8f05-57da245f170c.png)

doesn't work
![image](https://user-images.githubusercontent.com/29847057/216423871-d519991b-5b2d-4c67-a653-12702f4ec988.png)
![image](https://user-images.githubusercontent.com/29847057/216424228-421cdcaf-17b3-4993-a60a-ac2d0632124c.png)

**Expected behavior**

the functions to be found independently of the formatting of the file

**Platform:** 
 - OS: manjaro linux
 - vscode version: 1.74.3
 - extension version: v2.3.4

**Your Team Size Using TC:**

7, just me

**Comment by rangav** [comment]
Thanks @andresatierf for the reporting the bug, will look into it.

**Comment by rangav** [comment]
Hey we reached 1000 issues on GitHub 🎉. Did you notice you created 1000th issue?

**Comment by andresatierf** [comment]
Yeah, I did. I always find it funny when it hits some well rounded numbers.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v2.4.0`

### Thunder Client CLI
- https://github.com/rangav/thunder-client-support/releases/tag/v2.4.0

### Documentation
- For documentation read our blog post on [medium.com](https://rangav.medium.com/d91eb5c71d8e)

### Product Hunt
- We are launching today on [Product Hunt](https://www.producthunt.com/posts/thunder-client-cli), Please **upvote** and let us know any feedback.
