### ISSUE TITLE
Access localhost or 127.0.0.1

### ISSUE THREAD

**Issue by zkxil** [rangav/thunder-client-support#1086]
**Your Team Size Using TC:**

**Question:**
![image](https://user-images.githubusercontent.com/6679746/228169451-eba8a251-aa18-4d94-859b-21ab2b407986.png)

I used Vscode plugin to test API URL.
I want to see Thunder is a wonderful tool.
Things go well except I test it for localhost or 127.0.0.1,  get 403 error.
Could you tell me  what to do?
Thanks.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by frudolph77** [comment]
I think this is still an open issue.

I've tried Thunder Client against my local mockoon API mock. First thought damn it's not working/broken. Tried the StarWars API, everything is fine. And then dig through several issue to find a work around and to see that there is /will be no fix.
 
I've tried all combinations, only the combinations marked with an x work, and of course the real IP 
| lib   |localhost | 127.0.0.1 | 0.0.0.0 | [::1]
| -:| :-:|:-:|:-:|:-:|
| got | ||x |x |
| axios | || x ||
|postman| x | x | x | x |

There should be at least a note at a very prominent location, what has to be used instead of `localhost` or `127.0.0.1`.

From my point of view this needs to be fixed, it's common sense that these two terms are used when accessing a local server.

**Comment by rangav** [comment]
Hi @frudolph77 thanks for the feedback, Will research on how to fix this issue.

**Comment by rangav** [comment]
Hi @frudolph77 I am thinking of the solution.

if the localhost request fails with connection refused then automatically retry with any of ['127.0.0.1', '::1', '0.0.0.0'] to check which IP address works

Please let me know your feedback.

**Comment by frudolph77** [comment]
Some kind of retry in any combination of the possible addresses `['localhost', '127.0.0.1', '::1', '0.0.0.0']` would be great.

Sorry, I forget to mention that I did not get a connection refused, it's just an endless loading spinner. I've to cancel the request manually.

**Comment by frudolph77** [comment]
My real backend is a SpringBoot Application, I can't provide any piece of code from it.

But to reproduce just use [Mockoon](https://mockoon.com/). Download the portable version for Win or AppImage for Linux. Create just an environment, the default route in there is enough, and try to connect with Thunder Client.

For possible connections see updated matrix above.

I'm on Ubuntu Linux.

**Comment by rangav** [comment]
Thanks will look into it

**Comment by joseescoli** [comment]
Hey, all! Tested ThunderClient version 2.5.3 and works fine. Any version past 2.5.3 does not work anymore in Visual Studio Code.

**Comment by rtrom** [comment]
> Hey, all! Tested ThunderClient version 2.5.3 and works fine. Any version past 2.5.3 does not work anymore in Visual Studio Code.

This worked for me and my team, thanks!

**Comment by frudolph77** [comment]
I can confirm that Version  `2.10.2` mentioned in #1253 also solves the issue with the local addresses. No need to downgrade neither VS Code (Insiders) nor Thunder Client

**Comment by rangav** [comment]
Thanks for the confirmation, I will close the issue.

**Comment by JavascriptMick** [comment]
only http://[::1]:3000 worked for me with my nuxt dev server client using thunder v2.16.2

**Comment by joezsp** [comment]
Extension Settings: set "Request Timeout" 500 or more

**Comment by HK-RazieL** [comment]
[v2.24.0] - (2024-05-23) issue still persists regardless of if i used got or axios only [::1] worked for me

**Comment by zeekliviu** [comment]
[v2.24.13] - got the same problem, works only on [::1]

**Comment by m41w4r3exe** [comment]
[v2.24.13] - me too, works only on [::1]

I'm shocked for such famous extension with 4.6M downloads...
