### ISSUE TITLE
Pricing feedback old

### ISSUE THREAD

**Issue by rangav** [rangav/thunder-client-support#1170]
## Announcing Subscription Plans

The extension was free for the **last 2 years**, but to support the development and maintenance costs, we have to start charging businesses.

We are launching Subscription plans for businesses that use `Git-Sync` feature

- The core extension will be free without `Git-Sync`
- Businesses require to purchase subscription by **June 18th, 2023** to use `Git-Sync`
- The pricing is affordable when compared to Insomnia or Postman.

### Pricing

- **Free** - Use of extension without Git-Sync
- **Startup Plan** - $5 per user/month billed `monthly` or $3 per user/month billed `yearly`
- **Business Plan** - $10 per user/month billed `monthly` or $7 per user/month billed `yearly`
- **Enterprise Plan** - $15 per user/month billed `monthly` or $12 per user/month billed `yearly`

https://www.thunderclient.com/pricing

Please let us know your feedback below.

**Comment by rangav** [comment]
Hi All 

The extension was free for the last 2 years, but to support the development and maintenance costs, we have to start charging businesses. Otherwise, our startup company will be unable to maintain the project costs without generating revenue.

I hope you understand.

**Comment by baabale** [comment]
Dear team,

I wanted to express my concern about the recent announcement regarding the introduction of subscription plans for the Git-Sync feature. While we appreciate your efforts to support the extension's development and maintenance costs, we believe this decision is not in the community's best interest.

As an active user of the Git-Sync feature for the past two years, I have found it to be an indispensable tool in my workflow. However, the introduction of subscription plans means that businesses like ours will have to bear an additional financial burden to continue using this feature.

Given that many alternatives are available for version control and collaboration, we are disappointed that we will have to consider other options. We hope you will reconsider this decision and find a way to continue supporting the community without adding a financial burden to businesses.

Thank you for your attention to this matter.

Sincerely,

**Comment by TarekSalha** [comment]
I do not fully understand, what `git-sync` means? Does it mean, that I need to pay as soon I save my test collection into a git repo or does it mean, I need to pay as soon I work on the repo with others and share the collection?

**Comment by rangav** [comment]
Hi @TarekSalha 

Git Sync setting allows user to save requests data to workspace which is useful to share data with team.

These settings below 
https://github.com/rangav/thunder-client-support#git-sync

You need to buy a plan from June 18th to use these git sync settings

let me know if you have any further questions

**Comment by sanchez** [comment]
Completely understand and respect the decision to create a pricing structure, I wonder if you could change it so that free tier has a limited number of requests and add git-sync back in to free tier. That way teams could still evaluate the tool to it's full capacity without requiring to go through whatever internal hoops to get a paid license for that company.

Or possibly even just limit the number of executions that can occur within a given timespan?

**Comment by rangav** [comment]
Thanks @sanchez for the feedback, that's a good suggestion. Will review it.

**Comment by sanderkooger** [comment]
We have been using thunderclient for some time now, but since the last version suddenly our carefully built up API collections where unavailable. 

Now it seems they have been taken hostage in order to force a revenue model. 

I do get the fact that developing a client takes time. And you want to make some money off of that. I think it's completely out of bounds to deny people access to data they store in their own git repository. 

@rangav You need to think of other ways to monetize. Because disabling features out of the blue is outrageous. Especially if you deny users access to their own data that would be a function for ransomware, not for thunder client. 

For all users affected: in VScode in the extensions/thunderrclient tab there is the option to downgrade to version 2.7 This will still work without the carefully designed new hostage function. 

For all others, A simple google revealed this new project. https://hoppscotch.io/


@rangav Why not build an additional feature that you can charge for. Like automated testing from servers you host, or something like that. That way people will actually pay for a feature that you deliver, not monitizing a free feature from github? 

![image](https://github.com/rangav/thunder-client-support/assets/19397354/f5ce1ef7-09fc-47e9-8537-27683ea0cc16)

**Comment by rangav** [comment]
Hi @sanderkooger 

We are a startup company for profit, that needs to generate revenue to pay our bills and hire future employees.

We have mentioned in the [License](https://github.com/rangav/thunder-client-support/blob/master/LICENSE.txt) document clearly from the beginning, Currently, it is free to use, but the certain feature will be paid in the future.

Insomnia, Postman and Paw/RapidAPI  all charge for team features.

Hoppscotch raised [$3m dollars](https://company.hoppscotch.io/hoppscotch-raises-3m-in-seed-funding-to-build-open-source-api-development-ecosystem) funding they also have plans to charge for team features.

Our pricing is similar to all the existing API Clients that we are charging for Team sharing features. 

We also made our pricing more affordable than Insomnia and Postman

**Comment by titouanfreville** [comment]
Hope you will consider adding back git-sync in the free offer. I do not care paying for it for my personnal usage, but it can be a burden when starting project while git-sync is quite essential for most project. I would rather have to pay to save more environements/secrets/tests or collections than paying to save in git :pray:

**Comment by sanchez** [comment]
> We have been using thunderclient for some time now, but since the last version suddenly our carefully built up API collections where unavailable. 
> 
> Now it seems they have been taken hostage in order to force a revenue model. 

I came across a similar issue today but found just clicking the refresh button a couple of times and the collection showed up in thunderclient from git. I think this is possibly more a bug with the latest version and less a hostage situation

**Comment by sanderkooger** [comment]
Yes but you are not charging for a Thunderclient feature, You are charging for a github feature called git push.

If you where to actually build a real thing to monitize, like automated testing, ability to use API collections, API monitoring, ETC on a platform that runs on your infra. it would become a different story. 

I also saw something in your licence about this: 


PAYMENT
The license is free of charge currently.  
In future certain features will be paid features. You will need a License Key to use the paid features at that time and you are not allowed to use old free version of extension.

Nowhere does it state that you were going to deny users access to their own data. Legally, this means that you are liable for damages if the following requirements are met: 
- a company can prove damages due to the denial of access to their own code ( thunder_tests data)
- This degradement in service is not accidental.
- A motivator in court could also be that you deny access to the collections based on a financial motive.


Here is an example for your logic, Imagine GitHub suddenly decides that you only have access to your code after you pay them a sum. That would be a very, very bad day for the internet. 

And before you say it yes, I have seen the clause that makes updates mandatory, However this clause will not hold up in court. 

Like i said in a previous message, Thunderclient is a cool project, And there are far better ways to monetize it. But that would take building actual new features. 

Here is some food for thought: 

- Hosted testing and monitoring platform
- Hosted collections store
- hosted storage of collections
- Secret and env vars management that also intergrates with buildtools and has a CLI to pull secrets local if needed. 


 Those features i would gladly pay for. but not for storing a .json file in my git repo....

**Comment by sanderkooger** [comment]
> @sanderkooger you still have access to all the data till June 18th, We did not block any data. We have given 30 days time for users to make a decision.
> 
> As @sanchez said there could be a bug, Please restart your vscode that should fix the issue.

I needed to downgrade to be able to access my collections

**Comment by rangav** [comment]
@sanderkooger As I said you still have access to your data till June 18th, there is no denial of data.

Even after June 18th, you still have access to data and files in `thunder-tests` folder, Only our extension will not read data from custom storage folders.

I hope it's clear now.

**Comment by rangav** [comment]
@sanderkooger As a recent example Github Copilot was free for a few months at launch, then they added their pricing plans. Some users might have paid for subscription and others might have moved to other tools.

**Comment by sanderkooger** [comment]
> @sanderkooger As I said you still have access to your data till June 18th, there is no denial of data.
> 
> Even after June 18th, you still have access to data and files in `thunder-tests` folder, Only our extension will not read data from custom storage folders.
> 
> I hope it's clear now.

If you are telling me, i did not have to downgrade... You are wrong. Collections were not showing on the new version, and a pop up telling me it is a subscription feature led me here. 

You might want to recheck your code.... but my argument still stands. 

You are charging for a GIT feature, not a ThunderClient feature. And one that is easy to bypass at that. It just means making a seperate repo and using user storage location to init that repo... Meaning not only are you charging for a git feature, It is completely bypassable if needed. 

Other suites offer more services that only an API collection, So the argument there are moot.

**Comment by sanderkooger** [comment]
> @sanderkooger As a recent example Github Copilot was free for a few months at launch, then they added their pricing plans. Some users might have paid for subscription and others might have moved to other tools.
> 
> I am still paying for a subscription to Copilot.

Are you hosting the data for copilot? Or is github spinning up servers like crazy to host that service?

**Comment by sanderkooger** [comment]
Anyhow, This might be a good moment for the ThunderCloud community to unite and build their own OS alternative. Im open for suggestions.

**Comment by rangav** [comment]
Hi @rauljmz thanks for the feedback. Will fix the typo.

How much pricing is it worth for you? e.g $36 per year.

**Comment by rauljmz** [comment]
@rangav, tough question, as I could probably make do with free tools; but I would consider it it was ~ $20 a year.

**Comment by rangav** [comment]
@rauljmz Thanks, your feedback is noted.

**Comment by kobmik** [comment]
Our devices in the company don't have direct access to the internet. The Git Repo is hosted internally.
How can we activate the premium feature "Git sync" without internet access?

**Comment by rangav** [comment]
@kobmik Currently, you need to log in through the internet to activate premium features. What is your suggestion in this use-case?

**Comment by rangav** [comment]
Hi All, Quick update,

We have reduced the pricing of startup and business yearly plans to make them even more affordable.

- Startup plan reduced to **$36 per user/year** ( i.e $3 per user/month) 
- Business plan reduced to **$84 per user/year** ( i.e $7 per user/month)

**Comment by rangav** [comment]
Hi @Azim-Palmer 

We are charging users to store data in a custom location, a feature useful for team sharing.

We have nothing to do with git or any other source control you choose. That is up to the user to choose the source control.

We think that is the only feature worth charging users for. Every business needs to generate revenue to sustain the development and operational costs.

But let us know if you have any other suggestions on how we can charge users other than git-sync?

**Comment by rangav** [comment]
The only way I can think of is to charge like postman based on number of API calls? 

this will cost users a lot more than fixed monthly pricing.

**Comment by rangav** [comment]
> Hi, we were just about to switch over to this from Postman, Thunder looks like a great alternative.
> 
> 1. Can I confirm that Thunder client is trying to charge us to store request definitions in our **own** git repo?
> 
> On the assumption the answer to the above is yes :
> 
> 1. I understand the need to make this commercially viable
> 2. Hobbling a feature of another industry standard tool (git) is pretty distasteful to developers.
> 3. To be candid this was presented at the end of a stand-up and the swear-word ratio shot up considerably.
> 
> We were really keen to commercially support Thunder Client but preventing us from syncing our **own** files in our **own** repos is a massive red flag.
> 
> **EDIT**
> 
> To be clear this is not a price issue. This is a "Are they seriously trying to charge us for using our own repos? Wow what else are they going to try to pull down the road." issue.

To clarify, We are not controlling git here. The extension git-sync feature will allows user to save data in custom location that could be your git folder or a google drive folder or a network folder. 

Hope its clear now

**Comment by loxena** [comment]
Thank you for developing this great piece of software. The request data I have is only used by me. Is there a way I can save it that doesn't use the Git-Sync feature?

**Comment by rangav** [comment]
Hi @loxena, you can copy the files from git folder to a default storage location and disable the git setting `Save to Workspace`

Default storage location.
https://github.com/rangav/thunder-client-support#storage

**Comment by sanderkooger** [comment]
> Thank you for developing this great piece of software. The request data I have is only used by me. Is there a way I can save it that doesn't use the Git-Sync feature?

Store local and After that you create a symlink so the data is still stored in your git repo. That way you can use git as intended. No subscription needed.

The same way you would do with sites enabled in your apache dir

**Comment by aslansky** [comment]
@rangav I can totally understand to charge for a service or a software product. But you are technically charging user to be able to use a different path to save files to their own harddisk. There is no "sync". Sync to me would mean to have a service that keeps track of changes  and has decent merge capabilities (which might be worth 84$ per year). Neither of these features are provided by Thunderclient and are solely provided by the source control the user is using. So I can totally understand the frustration in this thread.

**Comment by rangav** [comment]
Hi @aslansky I got your point. 

What git-sync feature means clearly mentioned here, We are charging for the feature that allows users to store in a custom location. 
https://github.com/rangav/thunder-client-support#git-sync

As I said above I can change to charging based on number of requests executed using the extension, Which might cost than a fixed monthly pricing?

What is your suggestion here? how we should charge users?

**Comment by sanderkooger** [comment]
> Hi @aslansky I got your point. 
> 
> What git-sync feature means clearly mentioned here, We are charging for the feature that allows users to store in a custom location. 
> https://github.com/rangav/thunder-client-support#git-sync
> 
> As I said above I can change to charging based on number of requests executed using the extension, Which might cost than a fixed monthly pricing?
> 
> What is your suggestion here? how we should charge users?
> 

Hahaha maybe rename it to the gaslight feature then. Seems like no one believes what you are saying. Because we are all devs and actually know how it works. And that is nothing like what you describe. 

Unbelievable 😂😂😂

**Comment by rangav** [comment]
Hey @sanderkooger you want all the features for free or do you want us to charge users for different features and not git-sync?

What is your suggestion?

**Comment by sanderkooger** [comment]
No but charging for a local storage location... That's insanity. I think my previous messages had enough examples of how you could monitize in a good way. Probably make a few bucks more too.

By the looks of the responses I'm not the only one who would like to contribute financially. But if your going this route... Charging for where on their own hard-drive users store their own information. You will loose all those loyal supporters.

I'm going to say this flat out. You have way better options to launch and capitalize on. Services built arround thunder client. That way this project would be a brilliant marketing tool with 2m plus users.

But you can also choose to continue this madness and have a monitize plug-in with - 2m users

There my 2 cents for thought.

**Comment by rangav** [comment]
Hey @sanderkooger thanks for the suggestion, but we are not going in that route of cloud services. postman and insomnia and others are already providing them.

**Comment by sanderkooger** [comment]
> Hey @sanderkooger thanks for the suggestion, but we are not going in that route of cloud services. postman and insomnia and others are already providing them.

`if(!bool)

if(bool == false)

if(bool != true)

if(bool) {} else

if(bool.compareTo(!True) == 0)

if(!!!!!!!!!!!bool)`

😂😂😂😂😂😂😂

**Comment by vensauro** [comment]
like the others have said, i think that a cloud service is something good, because git is not the best way to save something on realtime, a cloud service that syncs the data for all devs can deliver more value for teams and companies, or something for non devs using the collections

**Comment by rangav** [comment]
Thanks @cw1934 for the great feedback

1. Yes you are right, git-sync name is causing confusion for few users, We will change it to Team features name.
2. We already have this in the roadmap, Which is also in the priority list.
3. Monetization: That's a good point about the short notice, Will consider increasing it to 60 or 90 days.
4. The plan is to add more features and new team members, the revenue generated from subscriptions will help achieve this.

**Comment by cw1934** [comment]
> 1. Yes you are right, git-sync name is causing confusion for a few users, We will change it to the Team features name.

@rangav I appreciate your reply, and am happy to hear the responses for items 2-4.  However, I have to respectfully disagree with this being branded as "Team" as well.  If I am a single developer, working on multiple projects, I would still need this capability to store ThunderClient files with the code for each respective project instead of having them all blended together.  This would be even more important for an individual consultant who needs to keep projects from different clients separate from each other.

**Comment by rangav** [comment]
@cw1934 What name do you suggest then?

**Comment by cw1934** [comment]
> like the others have said, i think that a cloud service is something good, because git is not the best way to save something on realtime, a cloud service that syncs the data for all devs can deliver more value for teams and companies, or something for non devs using the collections

While I can see this being of interest to some, one of the reasons that we gravitated so much to ThunderClient is the fact that it is local only, and shared only via Git.  We feel that the cloud functionality that Postman implemented is too convoluted, more intricate than we are interested in, and we don't see any need to pay Postman for the few Cloud hosting capabilities that we have readily available within our own infrastructure.

@rangav As another idea for future monetization, the ability to write/send the test results to a centralized resource that could present trend analysis would be very helpful.  The model I can see fitting closest is that of Dependency Tracker, where a Docker container can be self-hosted, and accepts REST requests with the information to be reported on.

**Comment by rangav** [comment]
@cw1934  Ok Then I will go with the Team Features name for now until we have a better name.

**Comment by Azim-Palmer** [comment]
> Hi @Azim-Palmer
> 
> We are charging users to store data in a custom location, a feature useful for team sharing.
> 
> We have nothing to do with git or any other source control you choose. That is up to the user to choose the source control.
> 
> We think that is the only feature worth charging users for. Every business needs to generate revenue to sustain the development and operational costs.
> 

I feel bad because I think with this one move you've alienated a huge part of your community, I think most people on this thread are desperately trying to quickly help prevent further damage.

I understand the position you're in, as others have said you're trying to convince developers that ThunderClient finds restricting changing a folder with the **intent** to make it harder for developers to use their own de facto team sync functionality is valid.

If you can convince developers of this I will be very surprised.

> But let us know if you have any other suggestions on how we can charge users other than git-sync?

Rather than **preventing** users from using our industry standard tools, which is making it harder to do the job, **create additional functionality that makes it easier to do the job**. Results visualisation, making it easy to continuously run smoke tests against an environment (building off of the CLI which is ace) etc. I'm not in the right mindset to explore options but respect you'll need product discovery on what's valuable to users & viable for the business.

If you want my honest feedback, I feel this is user-hostile and short-sighted. It's trying to force users to pay for the service when the alternative would cost you nothing, no ongoing infra costs etc for teams to store their own files in their own repos.

Developers are famous for thinking they can write the tools themselves (true or not), so trying to charge for what is effectively select directory functionality is incredibly off-putting.

I really really really wanted to switch to and commercially support ThunderClient, but based on this behaviour can't justify it for my teams.

Again, I think most people here are just trying to help you prevent irreparable damage to a great product.

**Comment by cw1934** [comment]
@rangav Exactly what @Azim-Palmer just commented, but worded far better than I could come up with.  Cheers to you both!

**Comment by rangav** [comment]
Hi @Azim-Palmer I got your point, there is not cloud costs. 

But other costs still apply 
- Development Costs
- Team Salaries
- Operational Costs
- Future development costs
- Support costs
- Sales Costs

This is the reason why we have made the pricing reasonable.

To charge users if you are expecting us to launch a cloud service and make the product more complicated then users will start complaining about other issues.

The subscription cost is for `complete extension software + team features` not just for those git settings.

Hope its clear now

**Comment by rangav** [comment]
> @rangav Exactly what @Azim-Palmer just commented, but worded far better than I could come up with. Cheers to you both!

Everyone is just taking is grated that extension software is free for commercial use.

The subscription cost is for `complete extension software + team features` to use for commercial purpose

**Comment by Azim-Palmer** [comment]
> Everyone is just taking it granted that extension software should be free for commercial use.

I hear you @rangav, I also work at a software based start-up and staff salaries are our main costs by far. It's also not easy finding a pricing model, people will always be unhappy.

That said, as mentioned earlier I was totally ready to give my Devs to go ahead to use ThunderClient and pay for licenses before this was flagged to me. We were absolutely prepared to pay because we're a business making use of your talent & efforts and I believe that should be rewarded.

You have more information than outsiders and whatever you choose to do you'll be doing with the intent of making your team successful, I genuinely wish you the best of luck.

**Comment by rangav** [comment]
Thanks @Azim-Palmer for understanding the current situation and the launch of the subscription. I have been working on this software full-time and for free for the last 2 years. It will be very difficult for me to do all the future work on my own without generating any revenue and hiring a team.

As you said, No matter what features I charge for there will always few users who will be unhappy. 

I am genuinely committed to building the best quality software and making it valuable for the users to pay a reasonable cost and use it.

**Comment by rangav** [comment]
### Update:
- I have created a [new thread](https://github.com/rangav/thunder-client-support/issues/1177) to give a better clarification on why we plan to charging users.
- We also increased the notice period to 90 days until `August 18th, 2023` to give enough time for businesses to make decision.

**Comment by rangav** [comment]
Please continue your discussion in the new thread below
https://github.com/rangav/thunder-client-support/issues/1177

**Comment by rangav** [comment]
Hi All,

I can think of an alternative way for a subscription plan ( not based on sharing features).

Here is my proposal.

**Fee Plan** 
- Limited Git features
- 1 Collection, 
- 1 Environment
- 25 requests can be added to the collection.

**Subscription Plan**
- Unlimited Collection, 
- Unlimited Environments
- Unlimited requests can be added to the collection.

I think either way both are similar to me, But let me know your feedback, If the above looks better to you?

Leave your feedback in the new thread https://github.com/rangav/thunder-client-support/issues/1177
