### ISSUE TITLE
It there a way to save tests without Git Sync?  It is cost-prohibitive for us but we like Thunder Client otherwise.  

### ISSUE THREAD

**Issue by bholman77** [rangav/thunder-client-support#1355]
**Please describe feature/problem details and the solution you'd like.**

**Describe alternatives you've considered**

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Hi @bholman77 

can you please answer below

- What is your team size using TC
- Have you read free version terms - https://www.thunderclient.com/terms#free-plan

**Comment by rangav** [comment]
Closing this issue as there is no response

**Comment by sturmenta** [comment]
@rangav how can I request to use the import or share collections functionality if my company meets exception 1?

> Exception 1: If your company's revenue or funding is less than 1 million dollars, then you can share or import collections and environments with other team members.

**Comment by rangav** [comment]
@sturmenta 

using free version you can share collection by manually exporting collection

**Comment by sturmenta** [comment]
ok, I know that you have to make some features paid in order to make your work worthwhile.
I used to use your extension in the past when this functionality was free and I love the extension

in case you want to know I ended up using postman extension and their collections to more easy way to sync with git
