### ISSUE TITLE
Postman-like cookie manager

### ISSUE THREAD

**Issue by maciejpankanin** [rangav/thunder-client-support#142]
In Postman there is Cookie Manager feature which allows creating cookies that are then shared added to all requests.

![image](https://user-images.githubusercontent.com/33896387/117938540-72607880-b307-11eb-9b94-4065e912ffc6.png)

It is especially useful with session cookies, would be great feature in Thunder Client 😀

**Comment by rangav** [comment]
Hi @maciejpankanin will add to roadmap

**Comment by diosby** [comment]
Please, add optionally add cookies to next requests. Thanks.

**Comment by diosby** [comment]
Please, add import cookies for existent requests.

**Comment by ekremkmz** [comment]
Is there any update on this topic?

**Comment by rangav** [comment]
Hi All,

Currently you can add cookie to request by using Cookie header, these cookies will be sent to all the following requests for that domain.

Earlier there was bug related to this which is fixed in v1.12.5 https://github.com/rangav/thunder-client-support/issues/164
<img width="779" alt="Screenshot 2022-04-14 at 19 37 56" src="https://user-images.githubusercontent.com/8637550/163456148-0b7ce090-9c6e-497a-9c07-3a6e75e884f0.png">

**Comment by davinishi** [comment]
up

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to v2.15.0

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.
