### ISSUE TITLE
Add Fast "Send" request on saved List of request

### ISSUE THREAD

**Issue by RexNext** [rangav/thunder-client-support#295]
HI , 
I want to suggest you , to add a tiny button send , to having sending request fast ... 
![image](https://user-images.githubusercontent.com/66295368/128587007-96fa3242-b7dc-4da8-9953-aa2d59059146.png)

**Comment by rangav** [comment]
Hi @RexNext thanks for the suggestion, will review it.

**Comment by natekwilson** [comment]
Would also love this feature, this would be extremely useful for debugging within VSCode.

**Comment by kevyntime** [comment]
I just found Thunder Client today while searching for this exact feature, but I was sold on the git sync feature anyway.

It would be helpful for workflow. Since we don't always need to change anything about the request, it would also be nice if the button could run the request without opening an editor. Maybe logging the response to the output console. That way Thunder Client can just live in the side panel and console unless something needs to be changed.

**Comment by rangav** [comment]
@kevyntime thanks for the feedback.

we are launching soon Thunder Client CLI, that will solve this issue.

Will provide more details when we launch cli feature.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.4.0`

You can now use CLI for quick send request much faster than UI.

### Thunder Client CLI
- https://github.com/rangav/thunder-client-support/releases/tag/v2.4.0

### Documentation
- For documentation read our blog post on [medium.com](https://rangav.medium.com/d91eb5c71d8e)

### Product Hunt
- We are launching today on [Product Hunt](https://www.producthunt.com/posts/thunder-client-cli), Please **upvote** and let us know any feedback.
