### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by jesielviana** [rangav/thunder-client-support#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by auyer** [comment]
Since the author did not add comments, I will:
Publishing to Open VSX allow your extension to be accessed by users of fully open source compilations of vscode, like [VSCodium](https://vscodium.com/) and [Code OSS](https://flathub.org/apps/details/com.visualstudio.code-oss).

VSCodium has a great documentation on why they exist, and the extensions : https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
I installed your extension directly from the `.vsix` file to test it, but it would be great to be able to download and update from the extensions tab ! :) 
Thanks !

**Comment by rangav** [comment]
Hi @jesielviana and @auyer it's in my list, but there are so many others things I need to finish first. 

If you can install this manually that good start, please post instructions here for others looking for the same.

**Comment by auyer** [comment]
## Quick manual installation guide: 

1- Go to the extension page on [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client)
2 - Click  "Download Extension"
![download_vsix](https://user-images.githubusercontent.com/12375421/116163086-75cfef00-a6cd-11eb-940f-a1688a9678c9.png)
3 - On your "Code" application, under the extensions tab, expand the "..." menu, and click "Install from VSIX"
![image](https://user-images.githubusercontent.com/12375421/116163225-bc254e00-a6cd-11eb-8d49-aa3bfa24332f.png)
4 - Now just add the file you downloaded on step 2 !

**Comment by rangav** [comment]
Hi All, I tried to create account in open-vsx.org, login with github account is the only option to create account?

**Comment by auyer** [comment]
Hi. I have not published a package myself, so I don't have an answer.

**Comment by rangav** [comment]
Hi all

finally managed to publish to open-vsx, now you can download from extensions tab
https://open-vsx.org/extension/rangav/vscode-thunder-client
