### ISSUE TITLE
Large Responses Freeze Up.

### ISSUE THREAD

**Issue by berellevy** [rangav/thunder-client-support#497]
**Describe the bug**
When I get a response that has a lot of text, (for example, 30 MB csv), the Response section freezes up.

This only happens when actually displaying the response. If I am viewing the headers for example, then there is no problem.
So it's probably too much to draw.

**Expected behavior**
I would propose to truncate large responses with an option to expand.

 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment]
Thanks @berellevy for reporting the issue, will look into it.

**Comment by rangav** [comment]
This issue is now fixed and published to marketplace as release version `v1.14.2`

Responses over 10MB will not display, But Instead will show option to download, You can change the limit in vscode setting `Response Limit`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.2

Let me know if any feedback
