### ISSUE TITLE
Update license to established type

### ISSUE THREAD

**Issue by kensgists** [rangav/thunder-client-support#501]
Issues #157 and #154 request the addition of a license for Thunder Client. A license was added as a result.

Unfortunately, the hand-rolled license currently used is not an established permissive or copyleft license type, such as MIT, MPL, Apache, or GPL. The protocols for adoption of software at the firm I work for (a large US bank) require an established license type in order to ingest and use publicly available software.

Is it possible to add one of these common licenses, replacing the current license language, and register the license type within the Github and VS Code Extensions repos? This would allow us to use Thunder Client internally and give our developers a choice other than Postman.

**Comment by rangav** [comment]
Hi @kensgists thanks for the feedback, 

this is not open source library, have plans to commercialise and launch paid plans at later stage, that’s why license is not a standard license.

if you have issue with any particular point, happy to address it.

**Comment by rangav** [comment]
The license is prepared by a professional lawyer here in Ireland

**Comment by jcrben** [comment]
@rangav fyi the license and the language is confusing - it wasn't clear to me that an employee of a company could use it w/o utilizing the sharing features

![image](https://github.com/user-attachments/assets/878cb5ce-e7ba-4a5f-8b25-0576d0910732)

However, this comment suggests that it can be used by employees at a company https://github.com/thunderclient/thunder-client-support/issues/1177#issuecomment-1558518208
![image](https://github.com/user-attachments/assets/9f899e91-d55c-4803-9a79-0f309329f080)

Additionally, the license itself seems to say employees are OK, but it seems like they may run the risk of breaking the license. For example if an employee pays for the license personally, can they use it at their large employer? Since they would likely use premium features, I'm guessing not.
![image](https://github.com/user-attachments/assets/8a836968-b377-4df7-af69-f2cd1d163e19)


Maybe you could add a licensing FAQ.

**Comment by rangav** [comment]
@jcrben We do not offer a personal license plan. Any license you purchase can be used for both personal and business purposes.

**Comment by jcrben** [comment]
@rangav just to be totally clear, it's also totally ok for me to use the free version as an employee at a large enterprise with many thousands of employees?

**Comment by rangav** [comment]
@jcrben not ok. Your company needs to buy minimum of 5% should be paid users to use our free version 

terms link
https://www.thunderclient.com/terms#free-plan

**Comment by jcrben** [comment]
@rangav thank you - you might want to increase the visibility of this provision

in my comment above I included a screenshot of your comment from 2023 https://github.com/thunderclient/thunder-client-support/issues/1177#issuecomment-1558518208 
![image](https://github.com/user-attachments/assets/2eb01091-d340-4472-ac77-6220ec683ec2)

Not sure if the terms have changed but might want to go back and edit that comment so people don't get the wrong impression

To be clear, I'm not using the extension for business purposes, just trying to understand it better - thank you! And I don't blame you one bit for getting paid😄
