### ISSUE TITLE
Add Base URL in settings of an folder in collections 

### ISSUE THREAD

**Issue by iambhuv** [rangav/thunder-client-support#659]
So, like when creating a complete collection of endpoints of a single domain it's hard to change them all one by one 
so I'd request you to add something like a base URL for a folder or collection so it can automatically be applied as a prefix
and we can use relative paths :)

**Comment by wilmarques** [comment]
There's an alternative for that while it isn't available.

You can configure an Global Env variable and use it in all Requests.
Not perfect, but works :)

**Comment by rangav** [comment]
related #316

**Comment by Blackwidow-sudo** [comment]
> There's an alternative for that while it isn't available.
> 
> You can configure an Global Env variable and use it in all Requests. Not perfect, but works :)

Thats the way i did it, but now im asking myself if there is a good way to reference a path-parameter in your tests?
For example like: 
![thunderclient1](https://user-images.githubusercontent.com/60359431/181047501-653b305c-5fdd-49e2-b42e-e0a52eb21353.png)
![thunderclient](https://user-images.githubusercontent.com/60359431/181046662-602bedc1-5037-4a36-90c4-03c903a557e8.png)
So that i dont have to adjust the test every time i change the path-parameter in the query tab, if you know what i mean.

**Comment by rangav** [comment]
Hi @Blackwidow-sudo 

You can set path variable value from env variable via `{{variableName}}`

and you check in tests with env variable again

**Comment by rangav** [comment]
@Blackwidow-sudo that is the easier and standard way to test, what is your suggestion?

**Comment by Blackwidow-sudo** [comment]
@rangav
Hm, it would be nice if there was a way to easily reference a path-parameter on the Tests-tab in a value-field.
For example with some kind of syntax like:
![tc-tests](https://user-images.githubusercontent.com/60359431/181087234-05acf673-8fa5-4e47-bb52-c1398464e86c.png)
Kind of like a `URL` instance in JS where you can access the baseUrl and all the params.

**Comment by rangav** [comment]
@Blackwidow-sudo ok create a new feature request for this with your above screenshot we can discuss there.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
