### ISSUE TITLE
Test via terminal or Github Actions

### ISSUE THREAD

**Issue by chientrm** [rangav/thunder-client-support#764]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Test via terminal or Github Actions

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Thanks @chientrm for the feedback, will add to roadmap.

**Comment by rangav** [comment]
How you like the commands to look like in terminal? can you provide an example what your are thinking?

**Comment by chientrm** [comment]
> 

AFAIK, a command in this format is convenient.

```sh
npx thunderclient
```

The output formats list should include:
- Terminal output
- XML file
- CSV file

Return non-zero exit code when one of the test failed.

**Comment by PavanMudigondaTR** [comment]
XML needs be in standard JUnit XML format !

**Comment by rangav** [comment]
@PavanMudigondaTR  thanks for feedback, Will add to roadmap.

**Comment by rangav** [comment]
Related to #98

**Comment by rangav** [comment]
Hi All, development is finished, We are planning to launch Thunder Client CLI next week, which will have lot of new innovative features, stay tuned…

**Comment by wavveen** [comment]
Beginning or ending next week? I can't wait any longer! :)

**Comment by rangav** [comment]
@wavveen early next week.

**Comment by rangav** [comment]
Hi All, 

Hope you all used `CLI` tool, Please let me know your feedback about what you like and any improvements required?

**Comment by wavveen** [comment]
Hi, yeah really using the CLI tool here! We did a POC to check if TC is going to be the tool to setup our auto API tests, by executing requests with the CLI in an Azure DevOps pipeline.

We've got multiple environments like dev, tst, acc, prd. Probably going to run the automated API tests on both tst and acc. One improvement would be that we could pass in the environment (id/name) as an argument: tc --col 'colNameOrId -env 'envId'
For now I'm manipulating the thunderCollection.json and setting the envId right before execution.

Another improvement, maybe not related to the CLI tool completely, is that we would be able to run scenario's by picking/clicking together some already existing request. At the moment you would need to create a new collection and duplicate requests into this new collection. Which means a lot of maintenance because al all the duplicated requests.

And another improvement, not related to CLI completely, would be the ability to store requests per file and not all in one big thunderclient.json. Would make things much clearer when merging/working with GIT.

**Comment by rangav** [comment]
Thanks @wavveen for the feedback.

1. Will provide option to input environment via `--env 'name'`
2. Running selected requests could be tricky to implement. But you can save them to folder and you can run requests in folder instead of collection. Will research if there is any better way to do this.
3. Some users requested separate each collection into separate file. There are some advantages with this like git merges. The only disadvantage is the extension load time will increase linearly with number of files to read. Will research about this issue further.

**Comment by wavveen** [comment]
Thanks! One other thing: the ability to run Pre Filters before Pre Requests. I would like to be able to run some code, and depending on the outcome run a Pre Request.

**Comment by rangav** [comment]
> Thanks! One other thing: the ability to run Pre Filters before Pre Requests. I would like to be able to run some code, and depending on the outcome run a Pre Request.

Can you create a new feature request for this?

**Comment by wavveen** [comment]
done #1018

**Comment by rangav** [comment]
@wavveen Provide env while running collection or request is implemented, please update to `v2.4.2`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.4.2

Please let me know your feedback.

**Comment by rangav** [comment]
@wavveen I think we can run selected requests in cli using below format

`tc --req-list id1,id2,id3`

do you want to run selected requests from one collection or multiple collections?

let me know your feedback? I can implement it

**Comment by wavveen** [comment]
> @wavveen Provide env while running collection or request using `--env 'nameOrId'` is implemented.
> 
> * please update extension to `v2.4.2`
> * update CLI to `v1.0.6`
> 
> See all features released https://github.com/rangav/thunder-client-support/releases/tag/v2.4.2
> 
> Please let me know your feedback.

Going to test this on Monday, thanks!

**Comment by wavveen** [comment]
> @wavveen I think we can run selected requests in cli using below format
> 
> `tc --req-list id1,id2,id3`
> 
> do you want to run selected requests from one collection or multiple collections?
> 
> let me know your feedback? I can implement it

Yeah that would suffice for running "scenario's"! I need to be able to select from multiple collections... 

I was just wondering if reporting will work? As earlier on you told you need to run a collection to get reporting...

Thanks!

**Comment by rangav** [comment]
Not sure about reporting will try out and get back to you.

**Comment by rangav** [comment]
@wavveen here is update for run selected requests. It's implemented now.

How it works

- `tc --reqlist id1,id2` will run requests with id1 and id2. The request should be from `same collection`.
- The reports will work fine.
- if you like to run selected requests from multiple collections, then you need run multiple commands for each collection.
- Alternatively you can also use pre-request from a different collection.

Please update CLI to `v1.0.7` and let me know your feedback.

**Comment by rangav** [comment]
Hi, Now you can run **Multiple or All Collections** from CLI in `v1.1.0`

- Run **All** Collections using `tc --col all`
- Run **Multiple** Collections `tc --col colIdOrName1,colIdOrName2`
- Update CLI to version - **v1.1.0**

Release Notes:
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.
