### ISSUE TITLE
Support for collection/folder level variables

### ISSUE THREAD

**Issue by Santhosh136** [rangav/thunder-client-support#823]
Would be great if we can have collection level variables like postman. This will help us avoid switching between environments which requires multiple clicks.

**Comment by rangav** [comment]
Hi @Santhosh136 

we have attach env to collection in collection settings view

did you try that?

**Comment by Santhosh136** [comment]
Hi @rangav,
Yeah I've tried that.. thanks! It would be nice if we have folder level variables also...

**Comment by benoitmasson** [comment]
I'd like to add a use case:
my environments contain some variables shared among collections (dev/prod URLs), but I'd also like to use collection-level variables to add data shared across environments.

Attaching an env will not do the job, since then a collection would be tied to a dev/prod URL.

**Comment by rangav** [comment]
@benoitmasson then you can try use `global env` variables, which can be accessed from any collection.

**Comment by benoitmasson** [comment]
Hi, let me be more concrete:
- I have 2 web APIs in the same git repository, namely `foo` and `bar`, which share the same `thunder-tests` configuration folder. I have 2 collections, 1 per API, each one with its own base URL defined as `{{base_url}}` variable value
- I have 2 environments, dev and prod, with different different `base_url` variable values. Let's say that dev is `http://localhost:8080`, and prod is `https://{{app_name}}.company.com`

I would like to add the `app_name` variable to the collection, so that all 4 app-env combinations resolve correctly the final base URL. I'm not sure this is the best way to do it, but I wasn't able to find another one.
I don't think that shared global env variables would be a solution, since that would imply that either the `app_name` value or the `base_url` pattern is shared across apps or envs.

**Comment by rangav** [comment]
@benoitmasson I think having `app_name` variable in global env is easy option.

Or you can create 2 separate env for e.g `envA-dev `and `envB-prod` and attach them the each collection.

![image](https://user-images.githubusercontent.com/8637550/200344894-e1a0b496-a3ae-417e-82a1-a0a61f86beba.png)

**Comment by benoitmasson** [comment]
Thanks, but from my understanding, this would not work since then, both `foo` and `bar` in `prod` env would share the same `app_name` (whether it's taken from the shared global env, or from the same `prod` env) and hence the same base URL.

What I want is:
- `foo` (collection) in `dev` (env) to point to `http://localhost:8080`
- `bar` in `dev` to point to `http://localhost:8080`
- `foo` in `prod` to point to `https://foo.company.com`
- `bar` in `prod` to point to `https://bar.company.com`

**Comment by rangav** [comment]
then you can do the following

foo collection set baseUrl as {{baseUrl1}}
bar collection set baseUrl as {{baseUrl2}}

in `dev` env - **baseUrl1** set value to `http://localhost:8080`
in `dev` dev - **baseUrl2** set value to `http://localhost:8080`

in `prod` env - **baseUrl1** set value to `https://foo.company.com`
in `prod` dev - **baseUrl2** set value to `https://bar.company.com`

**Comment by rangav** [comment]
you are welcome. I am closing the issue, feel free to re-open if needed

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.14.0`

https://github.com/rangav/thunder-client-support/releases/tag/v2.14.0

Please test and let me know your feedback.
